# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ecf2cb7f66218a24bf08786675cf915bd6d43b951cc5e20324b781121dbc9ffca7f271cb3473d1fba266191649aa6181458cddaf3686ac1a95b680cb532d696

test:
  secret_key_base: a7d0b012d5165ae88640886e03a5f31ae3b5ad3a982a9e0a8107f3e15324db2ee4756990d016465d09172471d25eda9d7d9b491949e3c93d88fdcacfbdfa3eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
